name = "aemo-api-worker"
compatibility_date = "2025-03-18"
main = "src/api/index.ts"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

# Wrangler version 3 (v3) format for Durable Objects:
[durable_objects]
  bindings = [
    { name = "AEMO_DATA", class_name = "AemoData" }
  ]
  script_name = "aemo-data-logger"

# Indicate how we store migrations for your Durable Object,
# including an initial migration that sets up a new SQLite backend.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AemoData"]

[vars]
CLIENT_IDS = "[\"insert-some-uuid-here\", \"another-uuid-here\"]"

SIGNING_KEYS = """
[
  {
    \"private\":\"-----BEGIN PRIVATE KEY-----\\nABC123...\\n-----END PRIVATE KEY-----\",
    \"public\":\"-----BEGIN PUBLIC KEY-----\\nXYZ456...\\n-----END PUBLIC KEY-----\",
    \"start\":\"2025-01-01T00:00:00Z\",
    \"end\":\"2026-01-01T00:00:00Z\",
    \"revoked\":false
  }
]
"""