name = "aemo-api-worker"
compatibility_date = "2025-03-18"
upload_source_maps = true

main = "src/api/index.ts"
workers_dev = true

# Wrangler version 3 (v3) format for Durable Objects:
[durable_objects]
  bindings = [
    { name = "AEMO_DATA", class_name = "AemoData" }
  ]
  script_name = "aemo-data-logger"

# Indicate how we store migrations for your Durable Object,
# including an initial migration that sets up a new SQLite backend.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AemoData"]

[vars]
LOG_LEVEL = 'DEBUG'