name = "aemo-data-logger"
compatibility_date = "2025-03-18"

main = "src/index.ts"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

# This example uses a cron trigger to run every 5 minutes offset by 1 minute
# Important: Cron triggers are only triggered in the CF production environment,
# not in local dev environment. They won't run as expected locally unless emulated.
triggers = { crons = ["1,6,11,16,21,26,31,36,41,46,51,56 * * * *"] }

# Wrangler version 3 (v3) format for Durable Objects:
[durable_objects]
  bindings = [
    { name = "AEMO_DATA", class_name = "AemoData" }
  ]

# Indicate how we store migrations for your Durable Object,
# including an initial migration that sets up a new SQLite backend.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AemoData"]


[vars]
AEMO_API_URL = "https://visualisations.aemo.com.au/aemo/apps/api/report/5MIN"
AEMO_API_HEADERS = '{ "Accept": "application/json" }'