name = "aemo-api-worker"
compatibility_date = "2025-03-18"
upload_source_maps = true
compatibility_flags = ["nodejs_compat"]

main = "src/api/index.ts"
workers_dev = true

# Wrangler version 3 (v3) format for Durable Objects:
[durable_objects]
  bindings = [
    { name = "AEMO_DATA", class_name = "AemoData" },
    { name = "API_ABUSE", class_name = "ApiAbuse" }
  ]
  script_name = "aemo-data-logger"

# Indicate how we store migrations for your Durable Objects,
# including an initial migration that sets up a new SQLite backend.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["AemoData", "ApiAbuse"]

[vars]
LOG_LEVEL = "DEBUG"
# The following environment variables must be set as real secrets in production:
# CLIENT_IDS='["some-uuid-string","another-uuid-string"]'
# SIGNING_KEYS='[{"private":"---BEGIN PRIVATE KEY---","public":"---BEGIN PUBLIC KEY---","start":"2025-01-01T00:00:00Z","end":"2026-01-01T00:00:00Z"}]'
# RATE_LIMIT_MAX="60"
# RATE_LIMIT_WINDOW_SEC="60"