name = "api-worker"
compatibility_date = "2025-03-18"
main = "src/index.ts"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

# Example: Route-based config or environment-based config can go here.

# Durable objects
[[durable_objects]]
name = "AemoDataDO"
class_name = "AemoDataDurableObject"
# Use the new style annotation to store the DO in an SQL backend
# If not in open beta yet, you'll need to update this to your DO config
# like "type = 'node'".
# For reference, see additional CF docs.
type = "sql"
script_name = "aemo-data-logger"

[vars]
# JSON or single string containing client IDs
CLIENT_IDS = "[\"insert-some-uuid-here\", \"another-uuid-here\"]"

# JSON array of key objects
SIGNING_KEYS = """
[
  {
    \"private\":\"-----BEGIN PRIVATE KEY-----\\nABC123...\\n-----END PRIVATE KEY-----\",
    \"public\":\"-----BEGIN PUBLIC KEY-----\\nXYZ456...\\n-----END PUBLIC KEY-----\",
    \"start\":\"2025-01-01T00:00:00Z\",
    \"end\":\"2026-01-01T00:00:00Z\",
    \"revoked\":false
  }
]
"""